# Generated by Django 4.2 on 2023-06-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CadastroCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("idade", models.CharField(max_length=50, verbose_name="Idade")),
                ("telefone", models.CharField(max_length=50, verbose_name="telefone")),
            ],
        ),
    ]
