# Generated by Django 4.2 on 2023-06-30 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basiM7S1", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cadastrocliente",
            options={"verbose_name": "Cliente", "verbose_name_plural": "Clientes"},
        ),
    ]
