# Generated by Django 4.2 on 2023-06-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basiM7S1", "0002_alter_cadastrocliente_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadastrocliente",
            name="status",
            field=models.CharField(
                choices=[("inadimplente", "Inadimplente"), ("adimplete", "Adimplente")],
                default="S/seleção",
                max_length=50,
                verbose_name="Status",
            ),
            preserve_default=False,
        ),
    ]
